project_id = "lypjdpbfvpznpttzthnh"

[functions.ai-copilot]
verify_jwt = true

[functions.evaluate-goals]
verify_jwt = true

[functions.recommend-ebp]
verify_jwt = true

[functions.generate-active-ingredients]
verify_jwt = true

[functions.recommend-strategies]
verify_jwt = true

[functions.recommend-risks]
verify_jwt = true

[functions.recommend-timeline]
verify_jwt = true

[functions.recommend-pd]
verify_jwt = true

[functions.recommend-metrics]
verify_jwt = true

[functions.recommend-communication]
verify_jwt = true

[functions.recommend-budget]
verify_jwt = true

[functions.ai-copilot-chat]
verify_jwt = true

[functions.get-shared-brief]
verify_jwt = false

[functions.synthesize-learning-plan]
verify_jwt = true
