UPDATE initiative_templates
SET decision_brief_template = jsonb_set(
  decision_brief_template, '{problem_statement}',
  to_jsonb(replace(
    decision_brief_template->>'problem_statement',
    'Research is unambiguous that tutoring works at 0.37 SD when dosage, group size, and consistency are protected',
    'Across 96 randomized trials, tutoring delivers roughly 0.3 SD when dosage, group size, and consistency are protected (0.29 SD in the peer-reviewed pooled estimate)'
  ))
)
WHERE name = 'High-Dosage Tutoring'
  AND decision_brief_template->>'problem_statement' LIKE '%unambiguous%';

UPDATE initiative_templates
SET typical_timeline = 'Materials and initial routines in place within 12 to 24 weeks; full-fidelity implementation across all K-2 classrooms is a 2 to 3 year arc, consistent with implementation-stage research. Progress monitoring runs throughout.'
WHERE name = 'Structured Literacy Program'
  AND typical_timeline LIKE 'Core implementation over 12%';

UPDATE initiative_templates
SET typical_timeline = 'Initial structures (screening calendar, intervention menu, data meeting cadence) in place within a semester; full-fidelity operation, with all tiers running and decisions consistently data-based, by year 2. Refine continuously through data cycles.'
WHERE name = 'MTSS/RTI Framework'
  AND typical_timeline LIKE 'Establish within a semester%';

INSERT INTO initiative_templates
  (id, name, category, description, evidence_base, target_outcomes, typical_timeline, resources_needed, active_ingredients, decision_brief_template)
VALUES (
  '3f8a2c10-5b7e-4d92-9c41-8e6f0a2b7d31',
  'Multilingual Learner (MLL/EL) Supports',
  'Intervention',
  'Schoolwide supports so multilingual learners access grade-level content while developing English: academic vocabulary taught intensively, oral and written English integrated into content instruction, regular structured writing, and small-group support where data shows need. Language development is the whole staff''s work, not a pull-out teacher''s alone.',
  'Built on the IES practice guide Teaching Academic Content and Literacy to English Learners in Elementary and Middle School (Baker et al., 2014), whose four recommendations carry moderate to strong evidence ratings under What Works Clearinghouse standards: teach academic vocabulary intensively across several days using multiple modalities; integrate oral and written English instruction into content-area teaching; provide regular structured opportunities to write; and provide small-group instruction for students struggling in literacy and English development. Goldenberg''s research syntheses (2008, 2013) support the same core: what is good for all learners is necessary but not sufficient for MLLs, who additionally need explicit language instruction attached to content. Evidence level: Strong for the four core practices; local outcomes depend on schedule protection and staff-wide ownership.',
  ARRAY['MLL access to grade-level content courses at parity with non-MLL peers', 'Growth on the annual English proficiency assessment for every proficiency band', 'Reclassification rates rising without post-reclassification slide', 'MLL representation in advanced coursework moving toward parity']::text[],
  'Vocabulary routines and writing structures within the first semester; integrated content-language instruction across departments is a 1 to 2 year arc with coaching. Small-group supports begin as soon as screening data identifies need.',
  ARRAY['Protected planning time for content and language teachers together', 'Academic vocabulary routine and shared word lists by course', 'Writing scaffolds and structured tasks in every content area', 'Small-group time in the master schedule, not only after school', 'Language proficiency data accessible to every teacher, not one office']::text[],
  '[{"name": "Intensive academic vocabulary", "is_core": true, "description": "A small set of high-value academic words taught across several days with multiple modalities, in every content area rather than English class alone.", "look_fors": ["A named word set per unit, visible in the classroom and in student work", "Words taught across multiple days with speaking, writing, listening, and reading practice", "Students use the taught words in their own sentences, not only match definitions"], "adaptable_boundaries": ["Which words are selected, provided they are high-utility academic terms", "The routine''s exact format, within the multi-day multi-modality core"]}, {"name": "Language woven into content instruction", "is_core": true, "description": "Oral and written English development integrated into science, math, and social studies teaching, so language grows through content rather than in isolation.", "look_fors": ["Content lessons include structured student talk, not only teacher explanation", "Language objectives sit beside content objectives where the model calls for them", "MLLs are placed in grade-level content, with scaffolds, rather than tracked out of it"], "adaptable_boundaries": ["How language objectives are written and displayed", "Scaffold selection per course and proficiency band"]}, {"name": "Regular structured writing", "is_core": true, "description": "Frequent short writing tied to content, with scaffolds matched to proficiency level and feedback on both ideas and language.", "look_fors": ["Writing happens in content classes weekly, not only in English class", "Scaffolds differ by proficiency band rather than one worksheet for all", "Feedback addresses meaning first, language second, and never only grammar"], "adaptable_boundaries": ["Task formats and length", "Which scaffolds are used at each band"]}, {"name": "Small-group support driven by data", "is_core": true, "description": "Students struggling in literacy or English development receive small-group instruction scheduled inside the day, formed and re-formed by data.", "look_fors": ["Groups exist in the master schedule, not only after school", "Membership reviewed against data at least monthly, with movement in and out", "Group instruction targets the diagnosed need rather than generic homework help"], "adaptable_boundaries": ["Group size and meeting frequency within program minimums", "Who delivers it, provided they are trained"]}, {"name": "Staff-wide ownership", "is_core": false, "description": "Every teacher of MLLs is a language teacher; the EL specialist coaches and coordinates rather than carrying the load alone.", "look_fors": ["Content teachers can name their MLLs and each one''s proficiency band", "The specialist''s calendar shows coaching and co-planning, not only pull-out", "PD on MLL strategies reaches content teachers, not only the EL team"], "adaptable_boundaries": ["The coaching and co-planning model", "How specialist time is allocated"]}]'::jsonb,
  '{"problem_statement": "Multilingual learners at [school] are [X] percent of enrollment and growing, but access, growth, and outcomes lag: [X] percent sit in below-grade-level tracks, reclassification averages [X] years, and post-reclassification performance slides. Language development is currently owned by [describe current structure], which cannot reach every classroom where MLLs spend their day.", "target_group": "All multilingual learners, with explicit attention to long-term ELs and newcomers as distinct groups with distinct needs.", "leading_indicators": ["Vocabulary routines observed in content classrooms", "Structured student talk and writing in content lessons", "Small groups running as scheduled with data-based membership"], "lagging_indicators": ["English proficiency growth by band", "Reclassification rate and post-reclassification trajectory", "MLL enrollment in advanced coursework"], "measurement_timeline": "Monthly walkthrough data on the four practices; proficiency growth at the annual assessment; reclassification and course-access review each semester."}'::jsonb
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO initiative_templates
  (id, name, category, description, evidence_base, target_outcomes, typical_timeline, resources_needed, active_ingredients, decision_brief_template)
VALUES (
  '7c4d9e25-1a3f-4b86-b5d2-9f0e6c8a4b17',
  'Check-In/Check-Out (Tier 2 Behavior Support)',
  'Behavior',
  'A structured Tier 2 intervention for students who need more than schoolwide expectations but less than individualized plans: a morning check-in with a consistent adult, teacher feedback on a daily point card at natural transitions, an afternoon check-out, and data reviewed weekly. It works through connection and predictability, not surveillance.',
  'Check-In/Check-Out is among the most-studied Tier 2 behavior interventions. Developed and researched by Hawken, Horner, and colleagues within the PBIS framework, it has repeated demonstrations of reduced problem behavior and office referrals for students whose behavior is maintained by adult attention; systematic reviews (including Maggin et al., 2015) classify it as an evidence-based practice for that population. The honest boundary: effects are weaker when behavior is escape-maintained, which is why the function check in the active ingredients is core, not optional. Requires a functioning Tier 1 (schoolwide expectations taught and acknowledged) underneath it. Evidence level: Strong for attention-maintained behavior within a working PBIS Tier 1; not a substitute for individualized support when data says more is needed.',
  ARRAY['Reduced office referrals for participating students within 6 to 8 weeks', 'Daily point card goal met on 80 percent of days after the first month', 'Graduation off the intervention with maintained behavior, not indefinite enrollment', 'Participation and outcomes equitable across student groups']::text[],
  'Two to four weeks to stand up (coordinator named, cards designed, staff trained, families informed); students typically participate 6 to 12 weeks with weekly data review; fading is planned from the start.',
  ARRAY['A coordinator with 30 to 45 protected minutes daily for check-ins and check-outs', 'Daily point card aligned to the schoolwide expectations', 'Weekly data review slot inside an existing team meeting', 'Staff training on feedback tone: brief, specific, non-punitive', 'Family communication plan, in home languages']::text[],
  '[{"name": "Consistent morning check-in", "is_core": true, "description": "The student starts every day with the same adult: greeting, card pickup, goal reminder, and a positive send-off.", "look_fors": ["Check-ins happen daily, on time, with the same adult or a named backup", "The tone is welcoming, not a behavior review of yesterday", "Students arrive at check-in on their own after the first weeks"], "adaptable_boundaries": ["Time and location", "Who coordinates, provided the person is consistent"]}, {"name": "Teacher feedback at natural transitions", "is_core": true, "description": "Each teacher rates the card briefly at the end of class with one specific comment, keeping feedback frequent and low-stakes.", "look_fors": ["Every rating slot completed, not left blank on hard days", "Feedback is specific to the expectation, delivered in under 30 seconds", "Ratings are honest: hard days are recorded as hard days"], "adaptable_boundaries": ["Card format and rating scale", "How ratings tie to the schoolwide expectations"]}, {"name": "Afternoon check-out and home connection", "is_core": true, "description": "The day closes with the coordinator reviewing the card, celebrating goal attainment, and sending a copy home on the agreed cadence.", "look_fors": ["Check-out happens daily with points totaled against the goal", "The home report goes on the agreed schedule, in the family''s language", "Missed goals end with a plan for tomorrow, not a lecture"], "adaptable_boundaries": ["Home communication cadence and format", "Recognition for goals met"]}, {"name": "Weekly data review with decision rules", "is_core": true, "description": "The team reviews each student''s point data weekly against written decision rules: continue, adjust, fade, or intensify.", "look_fors": ["Graphs reviewed weekly, with dates", "A written decision rule exists and is applied, not re-debated per student", "Students fade off with a plan; nobody stays on CICO all year by inertia"], "adaptable_boundaries": ["Which team owns the review", "The exact thresholds inside the decision rules"]}, {"name": "Function check before placement", "is_core": true, "description": "Before a student starts, the team confirms the behavior seeks adult attention; escape-maintained behavior gets a modified or different intervention.", "look_fors": ["A brief function screen is on file for every participant", "Students whose data does not respond in 4 weeks are re-assessed, not left enrolled", "Placement is by data and screen, not by referral frustration alone"], "adaptable_boundaries": ["The screening tool used", "How modified variants are designed"]}]'::jsonb,
  '{"problem_statement": "A small group of students, roughly [X] percent, accounts for [X] percent of office referrals. They do not need individualized plans; they need more structure, connection, and feedback than Tier 1 provides. Current responses are reactive and inconsistent across classrooms, which is exactly the condition under which these students do worst.", "target_group": "Students with repeated minor referrals whose behavior data suggests adult attention as the function; explicitly monitored for proportionality across student groups.", "leading_indicators": ["Daily participation rate in check-in and check-out", "Percent of rating slots completed by teachers", "Weekly point card goal attainment"], "lagging_indicators": ["Office referrals for participants", "Successful fade-off rate", "Demographic proportionality of placements and outcomes"], "measurement_timeline": "Daily point data; weekly team review against decision rules; six-week outcome checkpoint per student; semester equity review of placements."}'::jsonb
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO initiative_templates
  (id, name, category, description, evidence_base, target_outcomes, typical_timeline, resources_needed, active_ingredients, decision_brief_template)
VALUES (
  'b2e6f8a4-3c1d-4e79-a8b5-6d4f2c9e0a53',
  'Personal Device (Cell Phone) Policy',
  'Framework',
  'A schoolwide personal-device policy implemented as a change effort, not a memo: clear expectations co-developed with staff, students, and families, consistent adult follow-through, and honest measurement. The policy design matters less than the implementation consistency, which is why this is an implementation template rather than a rules document.',
  'The evidence here is emerging rather than settled, and this template says so. Beland and Murphy (2016, LSE Centre for Economic Performance) found that strict phone bans in English schools were followed by test score gains concentrated among lower-achieving students, suggesting distraction costs fall hardest on students with the least margin. Ward et al. (2017) found that a phone''s mere presence reduces available cognitive capacity even when unused. UNESCO''s 2023 Global Education Monitoring report recommends restricting smartphone use in schools where it disrupts learning. What the research does not yet establish: which policy design (full ban, pouch, classroom caddy, off-and-away) works best, or long-term effects. The strongest local evidence will be your own before-and-after data, which this template is built to collect. Evidence level: Emerging; strongest for the claim that inconsistent enforcement is worse than either clear permission or clear restriction.',
  ARRAY['Staff-reported classroom interruptions from devices drop within the first quarter', 'Enforcement actions distributed proportionally across student groups', 'Staff consistency: the policy applied the same way in [X] percent of observed classes', 'Student and family acceptance rising from launch baseline by mid-year']::text[],
  'One quarter to design with stakeholder input and communicate; launch at a natural boundary (semester or year start); first consistency and equity review after 6 weeks; policy revision window at the semester.',
  ARRAY['Storage mechanism if collection is chosen (pouches, caddies, lockers)', 'A one-page policy in student and family language, translated', 'Staff agreement on the exact response script for violations', 'A defined exception process (medical, accessibility, family circumstance)', 'Baseline data collected before launch: interruption counts, referral data']::text[],
  '[{"name": "Co-developed expectations", "is_core": true, "description": "The policy is built with staff, students, and families before launch, so enforcement rests on shared agreement rather than surprise.", "look_fors": ["Input sessions happened and changed at least something in the design", "Students can state the rule and the reason in their own words", "Families received the policy in home languages before day one"], "adaptable_boundaries": ["The policy design itself: ban, pouch, off-and-away, or hybrid", "How input is gathered"]}, {"name": "One consistent adult response", "is_core": true, "description": "Every staff member responds to violations the same way, with the same script and the same escalation path. Consistency is the active ingredient.", "look_fors": ["The response script is short, known, and used verbatim across classrooms", "No classroom operates a private variant of the policy", "Escalation is rare and follows the written path when it happens"], "adaptable_boundaries": ["Script wording", "Where confiscated devices are held and returned"]}, {"name": "Equity monitoring of enforcement", "is_core": true, "description": "Enforcement data is reviewed by student group from week one, because device policies are a known site of disproportionate discipline.", "look_fors": ["Enforcement actions logged, not handled informally and invisibly", "Data reviewed by student group at least monthly", "Disproportionality triggers a staff conversation, not a student blame cycle"], "adaptable_boundaries": ["The logging mechanism", "Review cadence beyond the monthly floor"]}, {"name": "Defined exceptions that do not swallow the rule", "is_core": true, "description": "Medical, accessibility, and family-circumstance exceptions exist, are private, and are honored without renegotiating the policy daily.", "look_fors": ["An exception process exists in writing and takes days, not weeks", "Exception holders are not publicly identifiable", "Exceptions are tracked so the policy''s integrity is visible"], "adaptable_boundaries": ["What qualifies", "How exceptions are documented"]}, {"name": "Before-and-after measurement", "is_core": false, "description": "Baseline interruption and referral data collected before launch, so the school learns what its policy actually did.", "look_fors": ["A baseline exists from before launch", "The same measures are re-collected at 6 weeks and semester", "Results are shared with staff and families, whatever they show"], "adaptable_boundaries": ["Which measures beyond the core set", "How results are communicated"]}]'::jsonb,
  '{"problem_statement": "Device interruptions at [school] are costing instructional time and adult energy: staff report [describe baseline], and current expectations vary classroom to classroom, which makes every enforcement moment a negotiation. The research base (LSE 2016, UNESCO 2023) suggests distraction costs fall hardest on students already behind, and that inconsistent enforcement is the worst position available.", "target_group": "All students; enforcement equity monitored by student group from launch.", "leading_indicators": ["Staff consistency in observed response to violations", "Logged enforcement actions per week", "Exception process turnaround time"], "lagging_indicators": ["Classroom interruption counts vs baseline", "Referral rates and their demographic distribution", "Staff, student, and family acceptance at semester"], "measurement_timeline": "Baseline before launch; six-week consistency and equity review; semester before-and-after comparison and policy revision window."}'::jsonb
)
ON CONFLICT (id) DO NOTHING;
